WCOR-1110: Add reCaptcha module.
Washington-County/COUNTY-DRUPAL pull request #114
Opened 2021-07-01 23:20 UTC by jmilden-git

### ODE XX

**Use case**

As a site admin, I want to enable reCAPTCHA for all public-facing forms.

**Implementation details**
Install and configure reCAPTCHA.

Dependencies
CAPTCHA module (already installed)

**Test plan**

As a site admin, I can place the reCAPTCHA field on a new webform.
As a site visitor (anon), I must pass the reCAPTCHA challenge to successfully submit a webform.

2021-07-01 23:39 UTC, gatoona requested changes
Please see comments relating to code.

Pending tasks:

- [ ]  Remove site_key and secret_key from commit.
- [ ] Generate the site key under the webteam's group Google account.
- [ ] Insert site_key and secret_key into secrets.settings.php

2021-07-01 23:39 UTC, gatoona commented on config/default/recaptcha.settings.yml
> +secret_key: 6LfigcYUAAAAADX6ARiY21OWi9zs7pMjW2ydMcb7
Hey @jmilden-git, we should not be committing secret keys/credentials into the public repo.

2021-07-02 00:02 UTC, jmilden-git commented on config/default/recaptcha.settings.yml
> +secret_key: 6LfigcYUAAAAADX6ARiY21OWi9zs7pMjW2ydMcb7
OK, those keys came from our existing reCaptcha Webteam account.  Is there another account I'm missing?  I don't see the secrets file in the repo.  Is this documented somewhere?

2021-07-02 15:43 UTC, gatoona commented on config/default/recaptcha.settings.yml
> +secret_key: 6LfigcYUAAAAADX6ARiY21OWi9zs7pMjW2ydMcb7
@jmilden-git take a look at https://docs.acquia.com/resource/secrets/

Also, looks like the site and secret key you used was for another site application and you added the ACP domains into that. Please remove them from that site and create a separate site with new site/secret key to implement.

I will have to go and delete this site now that the keys have already been compromised.

2021-07-02 21:11 UTC, gatoona approved these changes

2021-07-07 14:21 UTC, merged