WCOR-1113: Install Security Kit module and create initial configuration.
Washington-County/COUNTY-DRUPAL pull request #130
Opened 2021-07-23 19:39 UTC by lgbridges

### ODE XX

**Use case**

As a site administrator, I am maintaining a site that is aligned with best practices for web application security. Admins have some ability to configure / tweak application security settings via modular Drupal functionality. (Not all security reinforcement can be handled via modular functionality in admin UI.) Additionally, admins may have some auditing capability through module functionality in admin UI where appropriate.

**Implementation details**

Install and configure Security Kit module and any other well-tested, broadly implemented security reinforcement / auditing modules that will help admins quickly assess security posture.

Initial implementation will set Content Security Policy to "Report Only". A later story will finalize CSP to ensure compatibility with externally hosted site components.

**Test plan**

As a logged in user, the site will load without issue.

**Post-merge:** Temporarily remove HTTP Auth from Dev site and allow Tenable.io site scan to occur. Review results and further refine configuration.

2021-07-23 19:49 UTC, lgbridges commented
composer.lock issue not immediately resolveable -- will need additional time to prepare this for QA.

2021-07-28 20:43 UTC, gatoona requested changes

2021-07-28 20:43 UTC, gatoona commented on config/default/seckit.settings.yml
> +  origin: true
Enabling "HTTP Origin" presents an issue in IDE where saving settings leads to an 'access denied' error. Should use config split to disable for ah_other.

2021-07-28 21:00 UTC, gatoona approved these changes

2021-07-28 21:01 UTC, merged