Feature/wcor 1133
Washington-County/COUNTY-DRUPAL pull request #138
Opened 2021-08-03 23:33 UTC by jmilden-git

### ODE 120

**Use case**

As an editor or publisher, I want to manage the media with a group to which I belong.  Also need to be able to associate the group at the time I upload a media file.

**Implementation details**

Create a media entity view similar to the manage group content view. The manage group content view uses content revisions, but for media, you can use a media view instead of media revisions as we don't currently use workflow on media.

Use the group manage content view as a template for the type of fields you'll want to display in this table-based, admin-theme view.

Add the "Manage media" link to the group menu that shows "Manage content" using a similar strategy.

Update media library form display, add "Displayed in" field. (also added other fields)

**Dependencies**
Need media that is associated to a group for testing.  Upload new or use existing.

**Test Plan**

Go to view Manage Media, preview using node "206" for preview.  Inspect preview for file / fields.
Fields should be: Thumbnail, Name, Media Type, Changed, Added by
When uploading an image / document / video to media the "Displayed in" field is now present as a select list.

2021-08-07 00:30 UTC, lgbridges requested changes
Please implement autocomplete widgets for group selection on media items.

2021-08-07 00:30 UTC, lgbridges commented on config/default/core.entity_form_display.media.document.default.yml
> -    type: entity_reference_autocomplete
Group selection will require autocomplete widget--we will have far too many groups for a select list. Please revert.

2021-08-07 00:30 UTC, lgbridges commented on config/default/core.entity_form_display.media.document.media_library.yml
> +    type: options_select
Group selection will require autocomplete widget--we will have far too many groups for a select list.

2021-08-07 00:30 UTC, lgbridges commented on config/default/core.entity_form_display.media.image.default.yml
> -    type: entity_reference_autocomplete
Group selection will require autocomplete widget--we will have far too many groups for a select list. Please revert.

2021-08-07 00:30 UTC, lgbridges commented on config/default/core.entity_form_display.media.image.media_library.yml
> +    type: options_select
Group selection will require autocomplete widget--we will have far too many groups for a select list.

2021-08-07 00:30 UTC, lgbridges commented on config/default/core.entity_form_display.media.video.default.yml
> -    type: entity_reference_autocomplete
Group selection will require autocomplete widget--we will have far too many groups for a select list. Please revert.

2021-08-07 00:30 UTC, lgbridges commented on config/default/core.entity_form_display.media.video.media_library.yml
> +    type: options_select
Group selection will require autocomplete widget--we will have far too many groups for a select list.

2021-08-07 00:33 UTC, lgbridges commented
QA revealed needed changes. The media items mentioned in test plan weren't assigned to node 206, so perhaps those assignments happened in your local but as content they didn't happen in Dev. I went in to assign a group to the media items but noticed the field_group is using select list widget. These will need to be autocomplete widgets given the number of groups we'll be managing.

2021-08-09 23:37 UTC, jmilden-git commented
@lgbridges I updated the test plan to hopefully make more sense.  Let me know if you run into any issues.

2021-08-10 23:49 UTC, lgbridges approved these changes

2021-08-10 23:50 UTC, merged