WCOR-1233: Update core to 9.3.0, handle multiple module updates.
Washington-County/COUNTY-DRUPAL pull request #296
Opened 2021-12-14 00:27 UTC by lgbridges

## ODE XX

### Use/Fix Case

Begin testing against 9.3 and other updates. Webform module requires a security update blocking Pipelines.

### Test Plan

- [ ] Load site.
- [ ] Create a page and view it successfully.

2021-12-14 02:22 UTC, lgbridges commented
Search API and Search API Solr seeing issues upon update; needs research. Will pursue separately.

2021-12-14 03:12 UTC, lgbridges commented
Feeds update seeing issues upon update; needs research. Will pursue separately.

2021-12-14 17:49 UTC, lgbridges commented
Shield update seeing issues upon update; needs research. Will pursue separately.

2021-12-15 18:15 UTC, jlwcor commented
@lgbridges quick question. What were the steps you took to update the webform module libraries?

2021-12-15 18:19 UTC, lgbridges commented
> @lgbridges quick question. What were the steps you took to update the webform module libraries?

@jlwcor I'm pretty sure it was `composer update drupal/webform --with-all-dependencies; drush updb; drush cr; drush cex` and commit. At that point, Pipelines wasn't happy with it though and seemed to need updates for 4 specific ckeditor dependencies, so I handled those separately (see the commit that follows).

2021-12-15 18:21 UTC, lgbridges commented
> @lgbridges quick question. What were the steps you took to update the webform module libraries?

@jlwcor I noted the 4 ckeditor libraries that Pipelines was complaining about and updated them individually with `composer update --with-all-dependencies`, then pushed that out as a separate commit after the webform update.

2021-12-15 18:25 UTC, lgbridges commented
> > @lgbridges quick question. What were the steps you took to update the webform module libraries?
> 
> @jlwcor I noted the 4 ckeditor libraries that Pipelines was complaining about and updated them individually with `composer update --with-all-dependencies`, then pushed that out as a separate commit after the webform update.

I see now that the version doesn't seem updated according to the status report in the ODE.

2021-12-15 18:26 UTC, jlwcor requested changes

2021-12-15 18:26 UTC, jlwcor commented on composer.json
> +    "drupal/core": "^9.3",
This shouldn't be in here as we are already using drupal/core-recommended

2021-12-15 18:26 UTC, jlwcor commented on composer.json
> +    "drupal/core-recommended": "^9.3",
Please keep version for core-recommended fix otherwise during pipelines install, it will install a different version.

2021-12-15 18:32 UTC, lgbridges commented on composer.json
> +    "drupal/core": "^9.3",
@jlwcor So I followed the gospel instructions at https://www.drupal.org/docs/updating-drupal/updating-drupal-core-via-composer. For installs using core-recommended, they call for `composer update drupal/core "drupal/core-*" --with-all-dependencies`. But I see that this has added drupal/core to composer.json where that didn't exist before.

So you're saying this should've just been `composer update drupal/core-recommended --with-all-dependencies`?

2021-12-15 18:33 UTC, lgbridges commented on composer.json
> +    "drupal/core-recommended": "^9.3",
OK, so `9.3` instead of `^9.3`.

2021-12-15 18:41 UTC, lgbridges commented on composer.json
> +    "drupal/core-recommended": "^9.3",
I will push this change.

2021-12-15 21:07 UTC, sharstine commented
@lgbridges - QA passes according to test plan. I created a test page (/hhs/test-page-qa-scott) with formatted text, document links, an image, and a video. The page rendered as expected as an admin and anonymous user. I tested several other miscellaneous things in Drupal and didn't encounter any issues.

2021-12-15 21:37 UTC, lgbridges commented
Superseded by #301.

2021-12-15 21:37 UTC, closed without merging