WCOR-0000: Add theme building and debugging to aid local development.
Washington-County/COUNTY-DRUPAL pull request #303
Opened 2021-12-16 19:11 UTC by if-nick

### ODE XX

**Use/Fix Case** 

Code updates resulting from stand up meeting. These add Lando and Drupal configuration helpful for site building. 

**Implementation Details**

- `.lando.yml` updated.
- This allows building the production version of the theme with a `lando build-theme`
- Or building the development version of the theme with a `lando watch-theme`
- Also, allows turning on Xdebug for local development and IDE debugging with a `lando xdebug-on`

**Dependencies**

- 

**Test Plan**

-

2021-12-16 19:45 UTC, jlwcor requested changes

2021-12-16 19:45 UTC, jlwcor commented on docroot/sites/default/settings.php
> +$file = __DIR__ . '/settings.local.php';
Line 798 already checks to see if settings.local.php exists and includes it if found. This should work for the lando environment as well. Does the variable $app_root come up as undefined in Lando?

2021-12-16 22:45 UTC, joshuami requested changes

2021-12-16 22:45 UTC, joshuami commented on xdebug.ini
> +xdebug.idekey = vscode-xdebug
We may need to leave this out so that the Cloud IDE environments still have their correct xdebug settings. Maybe we could add this as a snippet to our wiki documentation. https://github.com/Washington-County/COUNTY-DRUPAL/wiki

2021-12-27 18:56 UTC, if-nick commented on docroot/sites/default/settings.php
> +$file = __DIR__ . '/settings.local.php';
Thank you for the catch. I haven't seen `app_root` come up undefined but will keep an eye out. The lines above have been removed.

2021-12-27 18:57 UTC, if-nick commented on xdebug.ini
> +xdebug.idekey = vscode-xdebug
Thank you for the suggestion. I've added `xdebug.ini` to the git ignore file and removed it from this pull.

2021-12-29 17:52 UTC, jlwcor commented
@if-nick looks like c2f4c8b reverted back some of the changes that were made.
Ex. readding the local.settings.php in settings.php

2022-01-05 17:07 UTC, jlwcor commented
Replaced with #344

2022-01-05 17:07 UTC, closed without merging