DRAFT: Activity/WCOR-19 Theme site navigation and header.
Washington-County/COUNTY-DRUPAL pull request #338
Opened 2021-12-28 19:50 UTC by if-nick

### ODE XX (pending)

**Use/Fix Case** 

Style and theme site header. [GitLab Ticket](https://git.ifsight.net/proj/clients/wcor/wcor-issues-internal-01/-/issues/19) 

DRAFT pending review and feedback. 

**Implementation Details**

- Branched off of `spike/WCOR-0000`, lando debugging updates, and `activity/WCOR-22`, initial SCSS variables work to support the style tile. 
- Adds CSS source maps to `webpack.mix.js`, helpful for finding the source of style rules in aggregated CSS files.
- Separates header template blocks into a separate file, `masthead.html.twig`, to isolate those sections and make the  parent template easier to work with
- Avoids overriding radix contributed-theme templates.
- Extends minimal Bootstrap color utilities (although they are available); the basics can be used in twig templates with writing extended, messy SCSS rules. For example adding `bg-faded-green` as a class to an HTML file without writing CSS rules. 
- Uses plain JavaScript for header javascript rules, relying on Webpack and the theme build steps for polyfills.
-

QUESTIONS: 
- Should search form HTML be moved elsewhere, or to a new navigation template
- Should header.js use different selectors 
- Do we need additional ARIA work now, or review accessibility later
- Others

**Dependencies**

- [insert here]

**Test Plan**

- [ ] Insert a test task here.

2021-12-28 19:51 UTC, if-nick commented
I intended to add labels for "draft" and "needs review" , and to tag some team members, but don't seem to have permissions to do so.

2022-01-07 20:24 UTC, jlwcor requested changes

2022-01-07 20:24 UTC, jlwcor commented on docroot/themes/custom/westy/westy.libraries.yml
> +    https://kit.fontawesome.com/fba24a4d16.js: { type: external, minified: true }
We are still exploring the option of using fontawesome.
In the meantime, are you able to use a css based approach for the icon? 
https://css.gg/search

2022-01-07 23:08 UTC, joshuami commented
@if-nick , was the form supposed to display on the CD environment for testing. I'm still seeing an oddity with the search form flyout.

![image](https://user-images.githubusercontent.com/4097978/148618612-3628f8de-a3d5-4547-8c91-fa4b5850fae2.png)

2022-01-10 21:49 UTC, joshuami approved these changes

2022-01-11 17:49 UTC, joshuami commented
@if-nick , the login link should get moved to the footer as a config change:

![image](https://user-images.githubusercontent.com/4097978/148994191-2c806b0f-8bc0-4397-aa1c-01ec67501126.png)

Do we need to add a label to the search form? It feels like it should read fine, but it is throwing an alert in WAVE.

![image](https://user-images.githubusercontent.com/4097978/148994351-12574073-98b9-44f6-bcc9-cddabc90ecd8.png)

It's not caused by this story, but the content column acted a bit weird at tablet levels. @lgbridges , we should get a story to address that.

![image](https://user-images.githubusercontent.com/4097978/148994610-c9daf693-4d5c-43cc-8857-527c8b4f8e0f.png)

The test plan has items that have not been addressed yet. It would be better to move those into a follow up story if we aren't going to test all of those before merging.

![image](https://user-images.githubusercontent.com/4097978/148995012-496c0b0d-dce3-441c-ab17-b00ca7241519.png)

2022-01-11 17:50 UTC, jlwcor commented
@if-nick can you provide a quick summary explanation on what is being changed in docroot/themes/custom/westy/webpack.mix.js ?

2022-01-11 18:49 UTC, if-nick commented
> @if-nick can you provide a quick summary explanation on what is being changed in docroot/themes/custom/westy/webpack.mix.js ?

There are two big changes in the webpack configuration- 

One checks if the current build is for production, as in Acquia environments or environments where a build is run with `mix --production`.  If not production we chained `sourceMaps` to the mix.  This enabled CSS source file mapping and would allow developers to inspect CSS to see what rules or files may be in use theming. 

The other was to add a SASS option for "quiet dependencies". The thinking there was that even though Bootstrap generates dozens of warning from the linter, they're not necessarily code and files we manage so the warning don't have lots of use. Reducing the amount of warnings should make identifying errors we do manage easier to spot and take care of.

2022-01-11 18:53 UTC, if-nick commented
> Do we need to add a label to the search form? It feels like it should read fine, but it is throwing an alert in WAVE.

I'm not sure if a <label>, hidden so it matches design, would be read by assistive technologies. I believe we're okay on this one and the WAVE documentation does say "If the form control is intuitive without a <label>, the title attribute value may be used."

2022-01-11 19:10 UTC, if-nick commented
> @if-nick , the login link should get moved to the footer as a config change

Thank you. Configuration updated and added

2022-01-11 19:45 UTC, merged