WCOR-1266: Sidebar nav updates.
Washington-County/COUNTY-DRUPAL pull request #417
Opened 2022-01-27 22:46 UTC by lgbridges

## ODE XX

### Use case

As a site visitor:

- I need a streamlined local/sidebar nav experience that doesn't include too many options, especially options that aren't relevant to my specific information need, such as siblings of the current page that are largely unrelated except for sharing the parent page or group that sponsors them.
- I need an additional "Return to parent" breadcrumb link at the bottom of the page to give additional visibility and power to breacrumbs as a means of navigating content.

As a site admin, I need to ensure that navigation menus contain at least 2 child items to appear.

### Implementation Details

This story shifts the orientation of sidebar nav to displaying only child menu items instead of showing both siblings and children. It also places the nav on the right sidebar, effectively leaving the left sidebar without operational blocks and therefore collapsed for every displayed node.

#### Why eliminate siblings from menus and only show children?

- It greatly reduces the amount of cognitive demand needed by users on a page, decreases the amount of overwhelm as they review the page and its nav.
- The content model should drive toward longer pages of closely related content. Where a model of more "atomic" pages is preferred by editors, there needs to be a more robust linking within body content to connect these shorter pages to weave sibling page content together. This needs to be discussed in editor training.
- Body content links, Related field, group homepage, and site search should be the connective tissue for related/sibling content (in that order).

Additionally, sidebar nav with only 1 child item will not be displayed. Site editors will need to add at least two child menu items to a page in order for nav to appear. The need for page content consolidation in a single child item scenario needs to be addressed in editor training.

### Test Plan

- [ ] As site visitor (anon), visit group at division level or lower (e.g. /mcfp) and verify that the sidebar nav is in the right sidebar below Contact Us. Confirm that only child pages appear.

As Eddie Editor:
- [ ] Create a new test page. In Menu Settings, check _Provide a menu link_ and choose a page or group as a parent.
- [ ] Repeat the prior step, giving the page a different title and short title. Choose the same menu parent as you did before.
- [ ] Visit the page or group chosen as the menu parent for the test pages and confirm that your test pages appear. Ensure that only child pages appear.

2022-01-27 22:50 UTC, jlwcor requested changes

2022-01-27 22:50 UTC, jlwcor commented on composer.lock
> +    "plugin-api-version": "2.2.0"
![giphy](https://user-images.githubusercontent.com/92542567/151456260-3c9d8317-0145-4fa7-b530-93174304bdaa.gif)

Annoying composer!

2022-01-27 22:51 UTC, lgbridges commented on composer.lock
> +    "plugin-api-version": "2.2.0"
Dang. I will fix.

2022-01-28 19:25 UTC, sharstine commented
@lgbridges - QA passes as test plan is written, with one exception: Eddie Editor doesn't have permissions to the menu settings on pages. I tested the Eddie Editor functions as an administrator instead.

Comments:

1. /housing/aloha-inn-permanent-supportive-housing: Suggest adding spacing between the Translation block and the menu in all viewports.

![translation_menu_spacing](https://user-images.githubusercontent.com/39655955/151607112-93ac4d7a-6435-4856-9209-d00694f44285.png)

2. In the "< Return to [parent]" area at the bottom of pages, the spacing between "to" and "[parent]" is slightly more than the spacing between "Return" and "to." Can we reduce the spacing before [parent]?

![return-to-parent-spacing](https://user-images.githubusercontent.com/39655955/151607206-8c62baa7-d7d3-4d8f-b2e7-8c1a3671189f.png)

3. It appears that the "Contact Us" block is only displayed on groups. While unrelated to this PR, I think there are cases when it would be helpful to display group contact information on pages as well: https://github.com/Washington-County/COUNTY-DRUPAL/discussions/369.

2022-01-31 19:29 UTC, jlwcor approved these changes

2022-01-31 23:42 UTC, merged