Update README.md
Washington-County/COUNTY-DRUPAL pull request #51
Opened 2021-05-18 02:31 UTC by lgbridges

Added QA Workflow section. Replaced catchup commands with 'blt custom:catchup'. Various minor edits.

2021-05-18 15:54 UTC, gatoona commented
Can we start incorporating anchor tags as our readme gets longer?
https://github.com/fefong/markdown_readme

2021-05-18 16:31 UTC, lgbridges commented
> 
> 
> Can we start incorporating anchor tags as our readme gets longer?
> https://github.com/fefong/markdown_readme

Yes, I will review and set this up.

2021-05-21 15:42 UTC, gatoona requested changes

2021-05-21 15:42 UTC, gatoona commented on README.md
> +    - Make a note in the ServiceIT story indicating that QA has passed.
Can this be done in GitHub?

2021-05-21 15:42 UTC, gatoona commented on README.md
> +    - Leave yourself as the *Additional Assignee* in the ServiceIT story for future reference about who performed QA.
Same as above. Can this be done in GitHub?

2021-05-21 15:42 UTC, gatoona commented on README.md
> +    - Move the item to the *Work in progress* column of the sprint tracking board.
This step seems redundant.

2021-05-21 21:15 UTC, gatoona approved these changes

2021-05-21 21:22 UTC, merged