WCOR-0019898: Create initial notification content type and block display
Washington-County/COUNTY-DRUPAL pull request #52
Opened 2021-05-19 19:59 UTC by lgbridges

2021-05-19 22:13 UTC, gatoona commented
Starting QA via ODE35

2021-05-19 23:52 UTC, gatoona commented
@lgbridges the only issue I ran into during QA is having the notifications show for its assigned group.
Problem seems to be from pathauto configurations.

Check out the new pattern set for the page content type. /admin/config/search/path/patterns
Instead of `[node:field_group]/news/[node:title]` it is now set to `[node:field_group:0:entity:field_group_path]/[node:title]`

This ensures the page uses only one and the short path from the group it references.

2021-05-20 00:05 UTC, gatoona commented on config/default/pathauto.pattern.news.yml
> +pattern: '[node:field_group]/news/[node:title]'
[node:field_group:0:entity:field_group_path]/news/[node:title]

2021-05-20 00:08 UTC, gatoona requested changes

2021-05-20 00:08 UTC, gatoona commented on config/default/pathauto.pattern.page.yml
> +pattern: '[node:field_group]/[node:title]'
[node:field_group:0:entity:field_group_path]/[node:title]

2021-05-20 00:08 UTC, gatoona commented on config/default/pathauto.pattern.news.yml
> +pattern: '[node:field_group]/news/[node:title]'
[node:field_group:0:entity:field_group_path]/news/[node:title]

2021-05-20 20:11 UTC, lgbridges commented
@gatoona -- ODE35 updated with the suggested changes.  Please test at your convenience.

2021-05-20 20:54 UTC, gatoona approved these changes
@lgbridges Able to create notice, assign it to group(s), and have it show for content listed under that group(s).

2021-05-20 20:56 UTC, merged